### ISSUE TITLE
No icons visible

### ISSUE THREAD

**Issue by stevelizcano** [Neet-Nestor/Telegram-Media-Downloader#10]
Currently running Telegram Web A 1.60.10 (web and webz.telegram.org) on chrome Version 112.0.5615.49 (Official Build) (arm64)

Not seeing any buttons available, script shows that it's initialized in the console :/

**Comment by dume2007** [comment]
Same issue

**Comment by Benkaz3** [comment]
run it on https://web.telegram.org/k - there should be no issues.

**Comment by Neet-Nestor** [comment]
Hi @stevelizcano and @dume2007 , could you please comfirm which webapp url are you using? I primarily tested on https://web.telegram.org/k/ as @Benkaz3 mentioned above, and I just noticed there're several other versions.
