### ISSUE TITLE
Doesn't work on t.me

### ISSUE THREAD

**Issue by otofoto** [Neet-Nestor/Telegram-Media-Downloader#13]
It doesn't work on t.me preview channels view.

**Comment by Neet-Nestor** [comment]
Hi, could you elaborate more on this issue and provide some links/screenshots please? I primarily tested on https://web.telegram.org/k/ so I'm not sure about t.me previews. Thanks.

**Comment by otofoto** [comment]
I mean visiting any channel preview from t.me.
Like - https://t.me/s/startupsi

**Comment by Neet-Nestor** [comment]
t.me is not supported in this script. Please use https://web.telegram.org/ instead.
