### ISSUE TITLE
"Save As" dialog box

### ISSUE THREAD

**Issue by toanchip1102** [Neet-Nestor/Telegram-Media-Downloader#15]
hi, sorry for my bad english. The scripts really work with me, thanks. Anyway, can u add "Save As" dialog box? i want to save file in many folder different. Thank you very much, you're the Best!

**Comment by Neet-Nestor** [comment]
Hi, thanks for the feedback (and no worry for the English as it makes total sense!).

The script currently works by triggering the default browser download behavior. Therefore, if you would like to have a pop-up save as dialog box every time you are downloading a media, I believe you can simply set this behavior in your browser's setting. For example, in Chrome you can toggle on settings->Ask where to save each file before downloading.

<img width="741" alt="image" src="https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/23090573/730bc564-21f8-4b4d-a7c7-322a0df8efbf">
