### ISSUE TITLE
IDM

### ISSUE THREAD

**Issue by harpo23** [Neet-Nestor/Telegram-Media-Downloader#17]
Hi, i wonder why this code can't be forward the download to idm
thanks

**Comment by Neet-Nestor** [comment]
I personally never used IDM before so I have several clarification questions:

1. Is IDM the [Internet Download Manager](https://www.internetdownloadmanager.com/)?
2. Is IDM requiring an URL for forwarding download there? How does the forwarding work?

**Comment by harpo23** [comment]
1.Yes
2.Yes, so the extension grab an url after you click download icon on any website and divide the file into multiple parts so the download become faster

**Comment by Neet-Nestor** [comment]
Then it makes sense that this script doesn't work for IDM. Telegram webapp is playing videos using HTTP streaming protocol for loading videos and this script achieved downloding by loading all trunks of the streamed video, assembling them together, and saving to local. In other words, there is no direct download url exists for the entire video.

Therefore, I guess we cannot support IDM until they have supported streaming downloading somehow.
