### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by Alex0510** [Neet-Nestor/Telegram-Media-Downloader#2]
![image](https://user-images.githubusercontent.com/22722447/175798848-9603c351-01b4-4f3b-b26b-70a12198ade2.jpeg)![image](https://user-images.githubusercontent.com/22722447/175798850-3db65ec9-89be-4fd6-af03-7bb105706f07.jpeg)

**Comment by Neet-Nestor** [comment]
重复issue #1， 关闭此issue，后续请在 #1 中继续讨论。

现在我可以看到你发的图片了。但是这些信息目前还无法让我确定问题所在。能请您试图在网页版telegram中打开一个视频，等待一小段loading使得视频播放器出现，然后如果视频播放器没有出现下载按钮的话，再截图一下console吗？

**Comment by Alex0510** [comment]
![image](https://user-images.githubusercontent.com/22722447/175909021-c7c2083b-72b4-40ca-b02e-7d985fc3f276.jpeg)
