### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by YuanNBB** [Neet-Nestor/Telegram-Media-Downloader#22]
hi，hope this can help you: https://github.com/tangyoha/telegram_media_downloader

**Comment by Neet-Nestor** [comment]
Thanks for your contribution! Would you mind creating a Pull Request to merge the change towards this main repo? I would like to have your name in the contributor to credit you for your valuable work!

Let me know if you don't want to do so, and I will just merge your code here manually.

**Comment by YuanNBB** [comment]
The repository is not mine， you can contact the author and merge the code

**Comment by Neet-Nestor** [comment]
Progress bar added in #45 .
