### ISSUE TITLE
Broken on firefox

### ISSUE THREAD

**Issue by jaimer0d** [Neet-Nestor/Telegram-Media-Downloader#25]
The last update made the script stop working in Firefox. 
>> Uncaught DOMException: Document.querySelectorAll: 'audio-element:has(.audio-waveform)' is not a valid selector

**Comment by Neet-Nestor** [comment]
Thanks for reporting. It seems like Firefox doesn't support this css pseudo-selector yet. I'll quickly update a fix.

**Comment by Neet-Nestor** [comment]
Fixed as 0522408a6ea3abd88df75d25c4a3b6c3e66bc786 ([version 1.031 on Greasyfork](https://greasyfork.org/en/scripts/446342-telegram-media-downloader)).
