### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by ytzhhws** [Neet-Nestor/Telegram-Media-Downloader#29]
Hi, sorry to open a new issue as the old one was just closed. 

Thanks for the latest update however it does not work. I did not see a download icon after the update in either k or a version, even worse, the download function via the hide icon of the old version is also lost. Actually the download works pretty good before update using the hided icon in version k as long as you know it is there, just can not see it. I just downgraded to the old version and everything is fine. Please look for any conflict in the updated version.

**Comment by Neet-Nestor** [comment]
Hi could you please share more detail? I'm asking for it since I tried it on my end, both version /k/ and version /a/ on Chrome, script version 1.041, and it works as expected.

It will be helpful if you provide your browser type and version, and copy your console output (especially any error message while you were using the tool) here.

To find the console output, open chrome devtools -> console.

**Comment by Neet-Nestor** [comment]
And it seems very weird to me as you mentioned it stops working for /a/ version too after the updating, since I didn't touch any code for version /a/ webapp in the last patch. Could you please try installing it in a clean state again?

**Comment by jusmallmann** [comment]
it downloads some files, then it "crashes" and doesn't download anymore, the download icon appears but the file doesn't download

**Comment by Neet-Nestor** [comment]
@jusmallmann Could you please attach the output of the console please? In my experiements yesterday, this happens sometimes but only when there's a network issue preventing the downloding. There's nothing wrong with the script nor any recent changes breaking it, so without a detailed console output I won't be able to investigate the issue. Thanks.

**Comment by ytzhhws** [comment]
I am in the outside, will upgrade again tomorrow to see if it works or not,
and let you know. Thanks!

Nestor Qin ***@***.***> 于 2023年9月9日周六 下午6:02写道：

**Comment by jynoh052** [comment]
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/75295154/82b38c28-0e17-487b-b0f7-8905b96163d4)
The above error occurs. Download not working at some point.

**Comment by ytzhhws** [comment]
Sorry for the late reply. I upgraded to the latest version and it works fine now, I will let you know if there is any new problem. Thank you for your work!

**Comment by Neet-Nestor** [comment]
Glad to hear the new version works. I will close this ticket, and feel free to re-open it if the same issue happens again.
