### ISSUE TITLE
cant download on telegram

### ISSUE THREAD

**Issue by wan3333** [Neet-Nestor/Telegram-Media-Downloader#32]
[Tel Download] 46n3muen.mp4: Error: Get non video response with MIME type text/html

**Comment by zzinggame** [comment]
same for me

**Comment by bichitoxxx** [comment]
same

**Comment by arzezio7** [comment]
Latest Version: 1.051 

![Screenshot 2023-10-16 191625](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/89209677/9e4d92a9-0b21-4014-9fb0-ff3cec93df24)

**Comment by accidentallyc** [comment]
Just dropping by, hopefully this will be helpful 😺 

When the button is already created and the  `setInterval` callback is called, the button isnt recreated effectively caching it. 
But I've noticed that in some scenarios the video src is loaded much later than when the button is added. 

Amending the "url" section to always get the URL before downloading the videos like in the screenshot below seems to have fixed most of my "not a video" issues.

![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/4762339/4842dbc7-7d12-44fa-a519-f4a63b726fea)

**Comment by Neet-Nestor** [comment]
Thanks @accidentallyc for taking a look and providing such an insightful suggestion! This is super helpful and I'll merge the change quickly.
