### ISSUE TITLE
下载过大的视频会OOM

### ISSUE THREAD

**Issue by ASAMUL** [Neet-Nestor/Telegram-Media-Downloader#35]
首先感谢开发人员的辛苦付出！
现在下一些大的视频（大概1g左右）就会出现OOM。我的电脑是DDR4 16G 2666频率，我有什么方法可以避免此情况吗？或者说是无法避免的？希望得到解答，十分感谢。
（应该不需要配图吧，现在在公司无法配图）

**Comment by Neet-Nestor** [comment]
出现的原因是目前下载过程中数据是在内存中暂存累积，直到下载完成保存为文件为止的。但是为什么16G内存会在1G左右就OOM的原因我不太确定，可能是OS或者浏览器本身有限制内存上限？

因为你的情况是电脑本身内存足够的，我会尝试先搜索下是什么限制了内存。如果和浏览器内存限制有关，看看有没有办法增加内存上限。

如果不行的话，另一个方法就是分块储存文件保存，之后再另行拼接了。但这个就会要求修改代码。修改本身不困难，但之后的拼接也需要额外自行处理。

**Comment by ASAMUL** [comment]
> 出现的原因是目前下载过程中数据是在内存中暂存累积，直到下载完成保存为文件为止的。但是为什么16G内存会在1G左右就OOM的原因我不太确定，可能是OS或者浏览器本身有限制内存上限？
> 
> 因为你的情况是电脑本身内存足够的，我会尝试先搜索下是什么限制了内存。如果和浏览器内存限制有关，看看有没有办法增加内存上限或者更换浏览器尝试。
> 
> 如果不行的话，另一个方法就是分块储存文件保存，之后再另行拼接了。但这个就会要求修改代码。修改本身不困难，但之后的拼接也需要额外自行处理。
感谢回答！应该是Chrome浏览器内存限制太小了，换了某国产浏览器就好了
