### ISSUE TITLE
Cannot download voice mesaage

### ISSUE THREAD

**Issue by jimmy12613** [Neet-Nestor/Telegram-Media-Downloader#37]
Seem no download button in voice message.
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/93816471/e0c064b6-1deb-4f28-9642-dfc52bdfa01f)

**Comment by yosoyx1** [comment]
Hi, change the version of Telegram to "K" (https://web.telegram.org/k) and the button I circled in the screenshot will appear.

![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/98092840/7ac87974-59ff-4b96-adc1-a53c8adf2bac)

**Comment by Neet-Nestor** [comment]
Hi, unfortunately right now the audio message downloading is only available on the /k/ version. I'll add this to the README file.
