### ISSUE TITLE
Video file is downloading in x-matroska format

### ISSUE THREAD

**Issue by kunalprakash1309** [Neet-Nestor/Telegram-Media-Downloader#40]
While downloading video file on chrome it get downloaded in x-matroska format.

**Comment by SaatoruGojo** [comment]
Follow these you can open your downloaded video file in .mp4

1. Run "VLC media player".(just run simple vlc form start - Don't open any video )
2. From main menu select "Media" > "Convert / Save...".
3. On "File" tab, click "Add..." button.
4. Choose you MKV file. After that, it should be added to the list. (Alternatively, you can drag&drop a file into the list.)
5. Click "Convert/Save" button.
6. Select Profile: "Video - H.264 + MP3 (MP4)".
7. Click on the icon button that has hint: "Edit selected profile".
8. On "Encapsulation" tab, leave "MP4/MOV" selected.
9. On "Video codec" tab, check both "Video" and "Keep original video track".
10. On "Audio codec" tab, similarly select both "Audio" and "Keep original audio track".
11. Click "Save" button.
12. In "Destination" selection, click "Browse" button to select directory and file name for you destination MP4 file.
13. Click "Start" button.
14. Observe progress bar in the main window as file is converted.
After that just close your vlc and go to the destination file and it  already created.
