### ISSUE TITLE
Seems not work?

### ISSUE THREAD

**Issue by lyscop** [Neet-Nestor/Telegram-Media-Downloader#41]
I open the video and press the download button then wait a while, there is no video download.

But the photo download worked.

https://web.telegram.org/k/

https://i.vgy.me/Vx8tPB.png

**Comment by davehudsons** [comment]
not working for me either.
firefox greasemonkey

**Comment by SebaX75** [comment]
Even in my situation there are issue and I'm unble to download the videos; I get the Aborted word on the progress bar when I try to start the download and it's immediate the output.
I've some basic code experience to resolve problem when someone explain me how to do, but not enought to debug this alone.
I've the video src tag extracted from html, but I'm unable to understand if the script have correctly parsed it to find the address of mp4 file... someone is able to help me and explain how I can do the debug?

Thanks

**Comment by Neet-Nestor** [comment]
@SebaX75 Could you please provide the logs in browser console? You can find it by following this article: https://balsamiq.com/support/faqs/browserconsole/#:~:text=Google%20Chrome,-To%20open%20the&text=You%20can%20also%20use%20Option,to%20select%20the%20Console%20tab.

**Comment by SebaX75** [comment]
Thanks for your reply.
This is the output in the console related to the script:
[Tel Download] video1949028867.mp4: URL: https://web.telegram.org/k/stream/%7B%22dcId%22%3A4%2C%22loc…deo%2Fmp4%22%2C%22fileName%22%3A%22video1949028867.mp4%22%7D Telegram Media Downloader:22:15
[Tel Download] video1949028867.mp4: Error: Non 200/206 response was received: 404 Telegram Media Downloader:27:15
    error user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:27
    fetchNextPart user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:229
    (Asinc.: promise callback)
    fetchNextPart user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:228
    tel_download_video user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:279
    onclick user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:642
    (Asinc.: EventHandlerNonNull)
    userScript user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:641
    (Asinc.: setInterval handler)
    userScript user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:546
    userScript user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:702
    scopeWrapper user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:723
    <anonima> user-script:https://github.com/Neet-Nestor/Telegram-Media-Downloader/Telegram Media Downloader:724
I collected some more infos using the advanced console, with only this yuo know the starting code.
This is the player code section encoded:
<video playsinline="true" src="stream/%7B%22dcId%22%3A4%2C%22location%22%3A%7B%22_%22%3A%22inputDocumentFileLocation%22%2C%22id%22%3A%225827777567016360239%22%2C%22access_hash%22%3A%228945238210682791724%22%2C%22file_reference%22%3A%5B2%2C123%2C41%2C217%2C177%2C0%2C0%2C0%2C12%2C101%2C158%2C97%2C5%2C151%2C198%2C46%2C136%2C133%2C225%2C240%2C141%2C21%2C68%2C98%2C73%2C153%2C142%2C184%2C247%5D%7D%2C%22size%22%3A636866549%2C%22mimeType%22%3A%22video%2Fmp4%22%2C%22fileName%22%3A%22video1949028867.mp4%22%7D" data-ckin="default" data-overlay="1"></video>
Going in the archive tab, cheching for the cache media chunks (seems that it download chunks of 1MB size and this is the second line), I found:
url:"https://web.telegram.org/5827777567016360239?offset=1048576&limit=1048576"
If I try to use this address directly, I get a 404 from ngnix server and not a file of 1MB as I could think.
One thing I would have liked to try to do, but wasn't able to, was to trace the files in the cache from the chunks to try to merge them and see the result with VLC... I can't figure out how to trace the file from the chunk.

Thanks,
SebaX75

**Comment by Neet-Nestor** [comment]
@SebaX75 Thanks for sharing. I got this error before too, and the solution I found is to switch to another browser.

This error is not from the script; instead, it's because somehow the Telegram server refuse the browser to request this video and returns 404 NOT FOUND, thus aborting the download. The root reason for this is still unclear to me.

Please try using Firefox if you are currently using Chrome, and vice versa as this used to work for me. You could also try clean your browser cookie and try re-login telegram, but I'm not sure whether it will work. You could also try incognito.

Let me know if it helps.

**Comment by Neet-Nestor** [comment]
I'm glad the issue resolved. I've noticed the icon issue (due to Telegram team replaced icon mapping again...) and have fixed it in v1.101.
