### ISSUE TITLE
Renaming the script?

### ISSUE THREAD

**Issue by Neet-Nestor** [Neet-Nestor/Telegram-Media-Downloader#46]
I begin to think that maybe "Telegram Media Downloader" is not the best name. Should we rename the script to give it more attentions?

Ideas:
- Telegram Video Downloader
- Telegram Private Video Downloader
- Telegram Downloader
- Others?

**Comment by hrukalive** [comment]
Looking at Google results, "Telegram Video Downloader" is definitely what ranks high when searching for "telegram" and "downloader" together.

**Comment by Neet-Nestor** [comment]
It seems changing script name will be hard as those users who already installed it won't get automatic updates anymore.

https://greasyfork.org/en/discussions/greasyfork/75556-when-a-script-name-is-changed-greasyfork-doesn-t-recognize-the-old-script

Let me think of a good way to update the name...

**Comment by hrukalive** [comment]
Maybe publish the script as new, and add an alert to the existing script to remind people to switch? idk lol

**Comment by Neet-Nestor** [comment]
Too much effort lol. I think I'll keep it as is and just add more related keywords in description.
