### ISSUE TITLE
右下角的下载提示框太大了怎么办？可以缩小吗，或者最小化吗？

### ISSUE THREAD

**Issue by xueli12** [Neet-Nestor/Telegram-Media-Downloader#48]
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/51438016/bf8d312d-5971-4b0a-92c0-8042c3dc9989)

**Comment by Neet-Nestor** [comment]
每个框右上角都有个关闭的小x按钮。貌似是颜色问题导致在这张截图里看不出来……我之后修改下颜色

**Comment by Neet-Nestor** [comment]
54b54a8350edfc5ff10f12b0749b8ec4d5bedbcd 修复了浅色模式下的按钮颜色。
