### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by benbenfree** [Neet-Nestor/Telegram-Media-Downloader#5]
I ues it in version k ,it show download button.But when i click it,it doesn't work.

**Comment by GitMadKing** [comment]
same here

**Comment by GitMadKing** [comment]
nevermind.

IT WORKS.

CLICK ONCE on download then WAIT il will prompt a download window when ready (i quess when file is completly downloaded)


SO

**CLICK ONCE

WAIT**

**Comment by Neet-Nestor** [comment]
Thanks for confirming.

Yes, currently once you clicked the button, you can check the download progress in browser console via logging. Once it finishes loading the entire video, it will trigger download.

I may later add more intuitive progress bar to avoid confusion. Thanks for the feedback.
