### ISSUE TITLE
Telegram restricted the Web API: Script stopped working

### ISSUE THREAD

**Issue by gerardbosch** [Neet-Nestor/Telegram-Media-Downloader#52]
Hi, 

Preasumably Telegram recently changed its API and now, downloading restricted media from web browser is no longer allowed. This is the user facing message:

![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/30733556/f0856f82-d9f5-4b0d-9214-dab9218121a8)

And the GET request triggered by the script download button returns a 404 upon Telegram endpoint call 😢

Is there any chance to make it work on the future?
Thanks

**Comment by gerardbosch** [comment]
It started to work again! I'm confused... but I close the issue. Maybe Telegram is doing something on their backend..? 🤷

**Comment by Neet-Nestor** [comment]
Sometimes Telegram Web returns 404, and the reason behind it stays unknown to me. Usually switching browser fixes the issue for me :)

**Comment by gerardbosch** [comment]
Good to know @Neet-Nestor, thanks. But what about the user message on the screenshot? Do you see this message too?
