### ISSUE TITLE
ios safari上可以用嘛

### ISSUE THREAD

**Issue by lyscop** [Neet-Nestor/Telegram-Media-Downloader#55]
安装了stay app，长按图片没显示下载按钮

**Comment by Neet-Nestor** [comment]
您好，我不太了解stay是什么。理论上本脚本需要利用油猴等进行注入。Safari理论可行，但是iOS Safari我不确定是否有类似插件帮助注入脚本。
另外这个插件不会修改长按图片的菜单，它是通过直接增加下载按钮在UI上实现的。考虑到移动端webapp可能UI不同，我也没有做过移动端测试，可能还是建议到电脑网页端使用。

**Comment by xyzbanana** [comment]
> 安装了stay app，长按图片没显示下载按钮

ios app userscripts extension it works, but exporting video to mp4.html data, image file I haven't tried yet, I'm looking for a way to open video file it
