### ISSUE TITLE
请问脚本会被限速吗？

### ISSUE THREAD

**Issue by HERAO12** [Neet-Nestor/Telegram-Media-Downloader#56]
我用这个脚本前两天速度突然开始变慢，速度下降一半不止，之前在挂上VPN上速度能有8M每秒，现在速度在几百kb至4MB之间跳跃，速度不稳定。
换上另一个脚本之后速度恢复，所以我比较奇怪。
（我是小白可能不懂这些，如果是我的问题请原谅，无意冒犯）
以下附图：
是我用本脚本和另外换的脚本速度对比图：
![1 (1)](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/150646238/5b41d051-acff-43da-8769-e193cb29b771)
![1 (2)](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/150646238/1deda513-c602-4dd7-92a6-a17ca652e868)

**Comment by Neet-Nestor** [comment]
脚本本身的原理是和正常通过网页端加载视频（类似于你手动点击视频加载播放），全部加载完成后保存本地。所以脚本本身没有做任何限速相关的设计，速度波动可能取决于你的网络和Telegram服务器之间本身的传输速度，浏览器的线程，或者Telegram那边一定的限速。当同时下载多个视频时已知Telegram那边可能会降低单个视频的宽带。建议可以多做一些尝试。
