### ISSUE TITLE
下载后有两个文件？/Two files after download?

### ISSUE THREAD

**Issue by Brother632** [Neet-Nestor/Telegram-Media-Downloader#63]
我的任务下载后有两个文件，无论我下载的什么格式的视频，将会有一个为crswap为后缀名的文件。例如我下载一个mp4文件，下载完成后我的mp4是0字节，但是多出来的crswap文件需要我手动改为mp4才能成为能播放的文件。开发者可以帮助我解决吗？或者是代码的问题，希望开发者能解决。谢谢~

My quest has two files after download, no matter what format video I download, there will be a file with the suffix crswap. For example, I download an mp4 file, after downloading my mp4 is 0 bytes, but the extra crswap file needs me to manually change to mp4 to become a playable file. Can developers help me solve this? Or it's a code problem, and I hope developers can solve it. thank you ~

**Comment by Neet-Nestor** [comment]
你好，请问能提供下你的os和浏览器版本吗？

**Comment by Brother632** [comment]
> 你好，请问能提供下你的os和浏览器版本吗？

![360截图20240524051954034](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/30917633/4c357d39-33a8-4bdc-bcf2-586e449e285a)

**Comment by Brother632** [comment]
> 你好，请问能提供下你的os和浏览器版本吗？

我刚刚试了一下最新的谷歌浏览器版本 125.0.6422.77（正式版本） （64 位）
都是一样的结果，还是会有crswap文件出现

**Comment by Neet-Nestor** [comment]
能再问下你的os种类和版本是什么吗？我本机没有出现过这个问题，刚刚搜索了下应该是操作系统的file API做的这个处理，通过生成临时文件避免重复写入，但是不知为何没有成功的在写入完成后用临时文件替换最终文件。

https://stackoverflow.com/questions/68131091/rename-filename-ext-crswap-to-filename-ext-rather-than-copying

**Comment by Brother632** [comment]
> 能再问下你的os种类和版本是什么吗？我本机没有出现过这个问题，刚刚搜索了下应该是操作系统的file API做的这个处理，通过生成临时文件避免重复写入，但是不知为何没有成功的在写入完成后用临时文件替换最终文件。
> 
> https://stackoverflow.com/questions/68131091/rename-filename-ext-crswap-to-filename-ext-rather-than-copying

我刚刚重新测试了，最新的谷歌浏览器下载完成后会替换crswap文件
但是我习惯用的浏览器是
360极速浏览器
版本号：13.5.2044.0
内核版本：86.0.4240.198
也就是该浏览器不会替换crswap文件

**Comment by Brother632** [comment]
> 能再问下你的os种类和版本是什么吗？我本机没有出现过这个问题，刚刚搜索了下应该是操作系统的file API做的这个处理，通过生成临时文件避免重复写入，但是不知为何没有成功的在写入完成后用临时文件替换最终文件。
> 
> https://stackoverflow.com/questions/68131091/rename-filename-ext-crswap-to-filename-ext-rather-than-copying

或许我需要更换浏览器使用了，因为我无法用我习惯的浏览器下载视频

Maybe I need to change my browser because I can't download videos with the browser I'm used to.

**Comment by Neet-Nestor** [comment]
好的，感谢update。看起来是浏览器版本导致的一个corner case。我刚刚检查了一下脚本代码应该是会正确的。预期行为是在下载完后脚本关闭下载流，随后浏览器+系统会处理临时文件管理的问题。

```javascript
_writable.close().then(() => {
  logger.info("Download finished", fileName);
});
```

我会建议暂时更换浏览器直到360浏览器更新解决此问题。

**Comment by Neet-Nestor** [comment]
关闭此issue因为这是浏览器环境导致的问题并且已找到临时解决方法。请在主流浏览器遇到这个问题是重新打开这个issue。
