### ISSUE TITLE
"Syntax error?"

### ISSUE THREAD

**Issue by Yasand123** [Neet-Nestor/Telegram-Media-Downloader#64]
The script's name is crossed with a red line, and there's a little note at the top that says "Syntax error?". I use Firefox.

Edit, here's a screenshot. Also, it works on Chrome fine, but not on Firefox. I use Violentmonkey for both browsers.
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/14009700/5919e99e-5fed-4243-890b-463118ec0ce0)

**Comment by Neet-Nestor** [comment]
Could you please share more detail, maybe a screenshot?

**Comment by Neet-Nestor** [comment]
<img width="371" alt="Screenshot 2024-05-29 at 2 37 33 PM" src="https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/23090573/5c3e6318-1543-48a1-b47b-cddfb4ce79ef">
Just tried violent monkey on Firefox and it doesn't give me error. Could you try reinstalling the script?
