### ISSUE TITLE
Can't download video from stories

### ISSUE THREAD

**Issue by NazZaR** [Neet-Nestor/Telegram-Media-Downloader#65]
Trying to download video from story (web status) and unable to do that. 
I gone further and looked in web inspector:
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/5753530/11fc9854-eded-4af7-a432-6afbaba98b2e)
Found a media url:
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/5753530/b4e08793-4042-4a7a-97e4-7e2a6929e368)
Opened it and even got browser's controls for video:
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/5753530/1009ef78-977d-4a8a-98b0-eca6031a02b4)
But it won't save. Right click-save, ctrl+s, hitting download button in browser controls gives me just an error:
![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/5753530/94ae3794-4896-468f-98c1-86bd93409931)

**Comment by Neet-Nestor** [comment]
The built-in download button in browser won't work since this is not a video file blob but a streaming url. You will need to have a script like Telegram Media Downloader to download it.

I have not tested it on stories for a while since I rarely used the feature. I will have a look and update you if I got time recently.

**Comment by mathewzile** [comment]
here's the code for /k/ webapp that works for me, inserted after the voiceMessages.forEach loop
`
    /* Stories */
    const storiesContainer = document.querySelector("#stories-viewer");
    if (storiesContainer?.innerHTML) {
      const storyHeaderRight = storiesContainer.querySelector("[class^='_ViewerStoryHeaderRight']");
      if (storyHeaderRight && !storyHeaderRight.querySelector(".tel-download")) {
        const downloadButton = document.createElement("button");
        downloadButton.className =
          "btn-icon rp tel-download";
        downloadButton.innerHTML =
          `<span class="tgico">${DOWNLOAD_ICON}</span><div class="c-ripple"></div>`;
        downloadButton.setAttribute("type", "button");
        downloadButton.setAttribute("title", "Download");
        downloadButton.setAttribute("aria-label", "Download");
        downloadButton.onclick = () => {
          // 1. Story with video
          const videoSrc = storiesContainer.querySelector("video.media-video")?.querySelector("source")?.src;
          if (videoSrc) tel_download_video(videoSrc);
          // 2. Story with image
          const imageSrc = storiesContainer.querySelector("img.media-photo")?.src;
          if (imageSrc) tel_download_image(imageSrc);
        };
        storyHeaderRight.prepend(downloadButton);
      }
    }
`
you may need to adjust it as i'm not a frontend developer so i don't know the compatibility stuff

unfortunately /a/ webapp doesn't work for me so i won't be able to help with that

**Comment by Neet-Nestor** [comment]
@mathewzile Thanks for the code snippet! I will work on merging this and also add support on /a/ webapp.

**Comment by Neet-Nestor** [comment]
Released v1.200, adding story download feature for both /k/ and /a/ webapps.

6bf88295e6a9057bd8e6b93362b728f633dbde26

**Comment by powerdollkirby** [comment]
> Released v1.200, adding story download feature for both /k/ and /a/ webapps.
> 
> [6bf8829](https://github.com/Neet-Nestor/Telegram-Media-Downloader/commit/6bf88295e6a9057bd8e6b93362b728f633dbde26)
> 
> ![Story Download](https://camo.githubusercontent.com/818265a5014f1158131847020c07e41b7630e9eb620c60b9cf4825b57e5a0361/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45785a335a355932567a4d32517a6257317863335a774e5451324e33513061336c6e616e7078645735356332517a616a6c354e585a7361435a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f784a466a424769386973485052356375486c2f67697068792e676966) [ ![Story Download](https://camo.githubusercontent.com/818265a5014f1158131847020c07e41b7630e9eb620c60b9cf4825b57e5a0361/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45785a335a355932567a4d32517a6257317863335a774e5451324e33513061336c6e616e7078645735356332517a616a6c354e585a7361435a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f784a466a424769386973485052356375486c2f67697068792e676966) ](https://camo.githubusercontent.com/818265a5014f1158131847020c07e41b7630e9eb620c60b9cf4825b57e5a0361/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45785a335a355932567a4d32517a6257317863335a774e5451324e33513061336c6e616e7078645735356332517a616a6c354e585a7361435a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f784a466a424769386973485052356375486c2f67697068792e676966) [ ](https://camo.githubusercontent.com/818265a5014f1158131847020c07e41b7630e9eb620c60b9cf4825b57e5a0361/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45785a335a355932567a4d32517a6257317863335a774e5451324e33513061336c6e616e7078645735356332517a616a6c354e585a7361435a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f784a466a424769386973485052356375486c2f67697068792e676966)

anyways to bypass this for private profiles/channels?
for private ones it will only download the previous channel/profile one
