### ISSUE TITLE
Button on top-right side cancels downloading

### ISSUE THREAD

**Issue by FreePhoenix888** [Neet-Nestor/Telegram-Media-Downloader#66]
The botton at the top-right side cancels downloading after some time
While the button under the video in its menu/toolbar(call it as you want) downloads video without a problem and with progress element

**Comment by Neet-Nestor** [comment]
Let me confirm, you are using /k/ webapp version right?

**Comment by FreePhoenix888** [comment]
I guess I was using A version with which other issues existed: https://github.com/Neet-Nestor/Telegram-Media-Downloader/issues/62#issuecomment-2137110098
Now I think everything is fine. I propose to close this issue
