### ISSUE TITLE
no download button

### ISSUE THREAD

**Issue by accountunavaible** [Neet-Nestor/Telegram-Media-Downloader#67]
there is no download button currently.

I've tried two versions of telegram web app. But no download button available on both

browser info: Chrome 125
os: windows 11
app: Telegram web 2.1.0K

thanks!

**Comment by accountunavaible** [comment]
I have to copy all the js code run in ternimal directly in order for it to work some how..

**Comment by Spikhalskiy** [comment]
Developer mode needs to be enabled for the script to work https://www.tampermonkey.net/faq.php#Q209
It may be worth adding it to installation steps of this script too.

**Comment by accountunavaible** [comment]
> Developer mode needs to be enabled for the script to work https://www.tampermonkey.net/faq.php#Q209 It may be worth adding it to the installation steps of this script too.

thank you for the help!

**Comment by Neet-Nestor** [comment]
@Spikhalskiy Thanks, I will update the installation guide to include this.
