### ISSUE TITLE
no download option available

### ISSUE THREAD

**Issue by guddu9079** [Neet-Nestor/Telegram-Media-Downloader#73]
no download option saw in right corner

**Comment by Neet-Nestor** [comment]
Please provide broswer model, Telegram webapp version, screenshots (if available) please.

**Comment by guddu9079** [comment]
now download is ok but after download video aborted and cancel

**Comment by Neet-Nestor** [comment]
Please attach console logs and network tab screenshot please. I cannot provide any help by only "it's not working.

**Comment by guddu9079** [comment]
![Screenshot 2024-06-27 131608](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/173984552/cf5ffa0b-ef95-483b-9f15-26b80f33d90d)
![Screenshot 2024-06-27 131820](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/173984552/15e6fd92-c193-44ac-abcf-c5e68110682c)

**Comment by Neet-Nestor** [comment]
Ah 403 issue. This sometimes happens to some users but I never got its root cause.

Could you try logging out of telegram webapp, maybe cleaning the website data, and logging in again? Otherwise, switching a browser works for some users too.

**Comment by guddu9079** [comment]
I log out telegram webapp and change browser but downloading is aborted 2 % after the download and cancel item.
Please help me this issue.

**Comment by guddu9079** [comment]
NOW WORK NORMALY
