### ISSUE TITLE
Can't delete or move downloaded audio files (.ogg)

### ISSUE THREAD

**Issue by rduwjjnh** [Neet-Nestor/Telegram-Media-Downloader#79]
After downloading audio files (.ogg) I can open and play them just fine but I can't delete or move them anywhere, when I press "Delete" nothing happens, and when I try to delete the audio file together with some other file it just hangs up like this:

![image](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/79216500/00e347af-f012-4fec-a7b8-673839fc6703)

I can delete the .crswap file if the download wasn't finished. I also can delete downloaded images and videos just fine.

Win10, Chrome 126.0.6478.127, Tampermonkey Beta.

**Comment by Neet-Nestor** [comment]
Seems a weird bug of Windows 10 file system. What is the size of the ogg files you downloaded?

**Comment by Neet-Nestor** [comment]
Unfortuantely I personally have little knowledge and little control on Windows file system. The script is simply calling the system API for storing the files. Therefore, I don't think this is an fixable bug for this project and I recommend you to check windows 10 help on this issue.

I tried searching for this issue and found many people complaining about this behavior. Could you try checking some of the discussions there and see if anything helps?
https://www.google.com/search?q=windows+10+delete+file+hangs
