### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by jwfaiai** [Neet-Nestor/Telegram-Media-Downloader#84]
目前不知道是我的原因还是脚本的原因，下载视频只能一个下好后再下第二个，不能一次下好几个，如果是脚本的原因希望能改进一下，麻烦作者了，投喂支持了

**Comment by Neet-Nestor** [comment]
是因为脚本使用的是Telegram自己的播放缓存逻辑，而这套逻辑自身会吃Telegram的限流（同时只能缓存一个视频）。这不是脚本本身的限制所以暂时想不到好的办法解决。
我记得telegram自身的下载按钮也是会排队一个一个下的，同时下载大量视频可能也会触发服务器那边的流量报警所以感觉保持现在这个方法可能比较安全。
