### ISSUE TITLE
音频右键无法显示下载按钮了，这是bug么，之前记得还可以，用的是k版

### ISSUE THREAD

**Issue by 0scarNiu** [Neet-Nestor/Telegram-Media-Downloader#96]
**Describe the issue**

**To reproduce**
1. Go to /k/ (or /a/) Telegram Webapp 

**Expected behavior**

**Screenshots**

**Environment:**
 - Browser: [e.g. Chrome, Firefox]
 - Tampermonkey (or other similar extensions) Version: [e.g. 4.11]
 - Script Version: [e.g. 1.0.0]

**Additional context**

**Comment by G11MODIII** [comment]
我也是，音频没有下载按钮

**Comment by Neet-Nestor** [comment]
如果问题仍然出现请重开这个issue。
