### ISSUE TITLE
作者大大用不了了插件，不显示下载按钮了

### ISSUE THREAD

**Issue by QING-Dd** [Neet-Nestor/Telegram-Media-Downloader#97]
**Describe the issue**

**To reproduce**
1. Go to /k/ (or /a/) Telegram Webapp 

**Expected behavior**

**Screenshots**

**Environment:**
 - Browser: [e.g. Chrome, Firefox]
 - Tampermonkey (or other similar extensions) Version: [e.g. 4.11]
 - Script Version: [e.g. 1.0.0]

**Additional context**

**Comment by Neet-Nestor** [comment]
我这边是没有问题的，所以请你根据这个模版提供你的截图或者任何报错，谢谢。

**Comment by QING-Dd** [comment]
油猴好像显示没调用插件，greasyfork评论里里好多和我一样情况

**Comment by Neet-Nestor** [comment]
Developer mode启用了吗？具体webapp的网址前缀是什么/

from README:
(Note, If you are using Tampermonkey extension in a Chrome-based browser, following [instructions](https://www.tampermonkey.net/faq.php#Q209) to enable Developer Mode.)

**Comment by QING-Dd** [comment]
打开开发者就可以了，感谢。以前不开可以正常用的，这几天才不行

**Comment by Neet-Nestor** [comment]
好，那我去用这个回复那些留言的。
